repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # - id: no-commit-to-branch # prevent direct commits to main branch
      - id: check-added-large-files # prevents giant files from being committed.
        args: ["--maxkb=3200"]
      - id: check-ast # simply checks whether the files parse as valid python.
      - id: check-builtin-literals # requires literal syntax when initializing empty or zero python builtin types.
      - id: check-case-conflict # checks for files that would conflict in case-insensitive filesystems.
      - id: check-docstring-first # checks a common error of defining a docstring after code.
      - id: check-executables-have-shebangs # ensures that (non-binary) executables have a shebang.
      - id: check-json # checks json files for parseable syntax.
      - id: check-shebang-scripts-are-executable # ensures that (non-binary) files with a shebang are executable.
      - id: check-merge-conflict # checks for files that contain merge conflict strings.
      - id: check-symlinks # checks for symlinks which do not point to anything.
      - id: check-toml # checks toml files for parseable syntax.
      - id: check-xml # checks xml files for parseable syntax.
      - id: check-yaml # checks yaml files for parseable syntax.
        args: ["--unsafe"] # checks syntax instead of attempting to load the YAML
      - id: debug-statements # checks for debugger imports and py37+ `breakpoint()` calls in python source.
      - id: destroyed-symlinks # detects symlinks which are changed to regular files with a content of a path which that symlink was pointing to.
      - id: detect-private-key # detects the presence of private keys.
      - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline.
        exclude_types:
          - plain-text
      - id: fix-byte-order-marker # removes utf-8 byte order marker.
      - id: trailing-whitespace # trims trailing whitespace.
        exclude_types:
          - plain-text
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        args:
          - "--ignore-missing-imports"
          - "--install-types"
          - "--non-interactive"
  - repo: https://github.com/jsh9/pydoclint
    rev: 0.8.3
    hooks:
      - id: pydoclint
        args:
          - --style=google
          - --check-return-types=False
          - --arg-type-hints-in-docstring=False
          - --treat-property-methods-as-class-attributes=True
          # - --arg-type-hints-in-signature=True
        # https://jsh9.github.io/pydoclint/config_options.html
