"""initial

Revision ID: 0001
Revises:
Create Date: 2026-04-14 15:37:49.615652+00:00
"""

from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "peaks",
        sa.Column("file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("num_peaks", sa.Integer(), nullable=False),
        sa.Column("peaks", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("mtime", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("file_path", "num_peaks"),
    )
    op.create_table(
        "tracks",
        sa.Column("file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("file_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("folder", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("artist_str", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("genre", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("bpm", sa.Integer(), nullable=True),
        sa.Column("release_date", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("release_year", sa.Integer(), nullable=True),
        sa.Column("original_artist", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("remixer", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("mix_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("has_artwork", sa.Boolean(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("file_format", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("is_complete", sa.Boolean(), nullable=False),
        sa.Column("missing_fields", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("mtime", sa.Float(), nullable=False),
        sa.Column("soundcloud_id", sa.Integer(), nullable=True),
        sa.Column("remixers", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("file_path"),
    )
    with op.batch_alter_table("tracks", schema=None) as batch_op:
        batch_op.create_index("idx_tracks_folder", ["folder"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tracks", schema=None) as batch_op:
        batch_op.drop_index("idx_tracks_folder")

    op.drop_table("tracks")
    op.drop_table("peaks")
    # ### end Alembic commands ###
