"use client";

import { CalendarDays, RefreshCw } from "lucide-react";
import { useQueryState } from "nuqs";
import { useCallback, useEffect, useMemo, useState } from "react";

import { FiltersToolbar } from "@/components/filters/filters-toolbar";
import { useTopBar } from "@/components/layout/top-bar-context";
import { LogoSpinner } from "@/components/logo-spinner";
import { Button } from "@/components/ui/button";
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";
import { WeeklyGroupCard } from "@/components/weekly-group-card";
import { api } from "@/lib/api";
import { useFilterState } from "@/lib/filters/use-filter-state";
import {
  fetchLikesPage,
  getMyLikedTracks,
  parseSCTimestamp,
  type SCPlaylist,
  type SCTrack,
} from "@/lib/soundcloud";

import { buildWeeklySchema } from "./build-weekly-schema";
import { useFollowingsTracks } from "./use-followings-tracks";
import {
  filterStateToWeeklyOptions,
  makeWeeklyFilterPredicate,
  useWeeklyFilter,
} from "./use-weekly-filter";
import {
  useWeeklyGroups,
  type GroupingMode,
  type WeekGroup,
} from "./use-weekly-groups";
import { useWeeklyPlaylists } from "./use-weekly-playlists";
import {
  WeeklyTreePanel,
  weekNodeId,
  type OrphanEntry,
  type WeekEntry,
} from "./weekly-tree-panel";

function buildPlaylistDescription(group: {
  start: Date;
  end: Date;
  playlistTitle: string;
}): string {
  const start = group.start.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    timeZone: "UTC",
  });
  const end = new Date(group.end.getTime() - 86400000).toLocaleDateString(
    "en-US",
    { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" },
  );

  // Calendar week
  const d = new Date(group.end.getTime() - 86400000);
  const dayNum = d.getUTCDay() || 7;
  const thu = new Date(d);
  thu.setUTCDate(d.getUTCDate() + 4 - dayNum);
  const yearStart = new Date(Date.UTC(thu.getUTCFullYear(), 0, 1));
  const cw = Math.ceil(
    ((thu.getTime() - yearStart.getTime()) / 86400000 + 1) / 7,
  );

  return `Autogenerated set of tracks from followed artists.\n${start} – ${end}, CW ${cw}`;
}

export default function WeeklyPage() {
  const [groupingMode, setGroupingMode] = useQueryState<GroupingMode>("mode", {
    defaultValue: "weekly",
    parse: (v) => (v === "biweekly" ? "biweekly" : "weekly"),
    serialize: (v) => v,
  });
  const [selectedId, setSelectedId] = useQueryState("node", {
    defaultValue: "",
  });

  const { tracks, loading, loaded, error, reload } = useFollowingsTracks();
  const {
    playlists: weeklyPlaylists,
    seenTrackIds,
    reload: reloadPlaylists,
  } = useWeeklyPlaylists();

  const groups = useWeeklyGroups(tracks, groupingMode);

  // Collection IDs
  const [collectionIds, setCollectionIds] = useState<Set<number>>(new Set());
  useEffect(() => {
    api
      .getCollectionSoundcloudIds()
      .then((ids) => setCollectionIds(new Set(ids)))
      .catch(() => {});
  }, []);

  // Seed schema fixes the attribute set so URL parsers stay bound even when
  // data-derived schema (genre options/counts, duration range) refreshes.
  const seedSchema = useMemo(
    () => buildWeeklySchema({ tracks: [], hasCollection: true }),
    [],
  );

  const {
    state: filterState,
    set: setFilter,
    clearAll: clearFilters,
  } = useFilterState(seedSchema);

  const filterOptions = useMemo(
    () => filterStateToWeeklyOptions(filterState),
    [filterState],
  );
  const { excludeOwnLikes } = filterOptions;

  // Liked track IDs
  const [likedTrackIds, setLikedTrackIds] = useState<Set<number> | null>(null);
  useEffect(() => {
    if (!excludeOwnLikes || likedTrackIds !== null) return;
    let cancelled = false;
    async function fetchAllLikedIds() {
      const ids = new Set<number>();
      let page = await getMyLikedTracks(200);
      for (const t of page.collection ?? []) {
        const parts = (t.urn ?? "").split(":");
        const id = parseInt(parts[parts.length - 1], 10);
        if (!isNaN(id)) ids.add(id);
      }
      while (page.next_href && !cancelled) {
        page = await fetchLikesPage(page.next_href);
        for (const t of page.collection ?? []) {
          const parts = (t.urn ?? "").split(":");
          const id = parseInt(parts[parts.length - 1], 10);
          if (!isNaN(id)) ids.add(id);
        }
      }
      if (!cancelled) setLikedTrackIds(ids);
    }
    fetchAllLikedIds().catch(() => {});
    return () => {
      cancelled = true;
    };
  }, [excludeOwnLikes, likedTrackIds]);

  const { filteredTracks: allFilteredTracks } = useWeeklyFilter(
    tracks,
    filterOptions,
    seenTrackIds,
    collectionIds,
    likedTrackIds ?? undefined,
  );

  // Filter predicate for tracks already in an existing playlist: apply every
  // filter except `excludeSeen` (those tracks are "seen" by definition and we
  // still want to show them in their own playlist).
  const inPlaylistPredicate = useMemo(
    () =>
      makeWeeklyFilterPredicate(
        { ...filterOptions, excludeSeen: false },
        undefined,
        collectionIds,
        likedTrackIds ?? undefined,
      ),
    [filterOptions, collectionIds, likedTrackIds],
  );

  // Per-group filtered tracks
  const groupsWithFilteredTracks = useMemo(() => {
    const filteredSet = new Set(allFilteredTracks);
    return groups.map((group) => ({
      group,
      filteredTracks: group.tracks.filter((t) => filteredSet.has(t)),
    }));
  }, [groups, allFilteredTracks]);

  // Global selection state
  const [selectedIds, setSelectedIds] = useState<Set<number>>(new Set());

  const toggleSelect = useCallback((id: number) => {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }, []);

  const rangeSelect = useCallback((ids: number[]) => {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      ids.forEach((id) => next.add(id));
      return next;
    });
  }, []);

  const selectGroupAll = useCallback((ids: number[]) => {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      ids.forEach((id) => next.add(id));
      return next;
    });
  }, []);

  const deselectGroup = useCallback((ids: number[]) => {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      ids.forEach((id) => next.delete(id));
      return next;
    });
  }, []);

  const playlistByTitle = useMemo(() => {
    const map = new Map<string, SCPlaylist>();
    for (const pl of weeklyPlaylists) {
      map.set((pl.title ?? "").trim(), pl);
    }
    return map;
  }, [weeklyPlaylists]);

  // Orphan playlists (outside 2-week feed window)
  const orphanGroups = useMemo(() => {
    const feedPlaylistTitles = new Set(groups.map((g) => g.playlistTitle));
    return weeklyPlaylists
      .filter((pl) => !feedPlaylistTitles.has((pl.title ?? "").trim()))
      .map((pl) => {
        const createdAt = (pl as Record<string, unknown>).created_at as
          | string
          | undefined;
        const date = createdAt ? new Date(createdAt) : new Date(0);
        const key = `orphan-${(pl as Record<string, unknown>).urn ?? pl.title}`;
        const title = (pl.title ?? "").trim();
        const group: WeekGroup = {
          key,
          label: title,
          playlistTitle: title,
          start: date,
          end: date,
          tracks: [],
          isCurrent: false,
        };
        return { group, filteredTracks: [] as SCTrack[] };
      })
      .sort((a, b) => b.group.start.getTime() - a.group.start.getTime());
  }, [weeklyPlaylists, groups]);

  // Only show groups that have tracks or an existing playlist
  const visibleGroups = useMemo(
    () =>
      groupsWithFilteredTracks.filter(
        ({ filteredTracks, group }) =>
          filteredTracks.length > 0 || playlistByTitle.has(group.playlistTitle),
      ),
    [groupsWithFilteredTracks, playlistByTitle],
  );

  // Active weeks tree entries. trackCount is the total the user would see if
  // they opened this week (existing playlist size + new feed tracks). Filters
  // like "exclude seen" intentionally do NOT shrink this total — it's the
  // actionable size of the week, not the filtered feed slice.
  const weekEntries: WeekEntry[] = useMemo(
    () =>
      visibleGroups.map(({ group, filteredTracks }) => {
        const pl = playlistByTitle.get(group.playlistTitle);
        if (!pl) {
          return {
            group,
            hasPlaylist: false,
            newCount: 0,
            trackCount: filteredTracks.length,
          };
        }
        const existingUrns = new Set<string>();
        for (const t of pl.tracks ?? []) {
          if (t.urn) existingUrns.add(t.urn);
        }
        const existingCount = pl.track_count ?? pl.tracks?.length ?? 0;
        const newCount = filteredTracks.reduce(
          (n, t) => n + (t.urn && !existingUrns.has(t.urn) ? 1 : 0),
          0,
        );
        return {
          group,
          hasPlaylist: true,
          newCount,
          trackCount: existingCount + newCount,
        };
      }),
    [visibleGroups, playlistByTitle],
  );

  // Past Weeks tree entries. Apply the same filter predicate to the orphan
  // playlist's own tracks so counts line up with what the table would show.
  // newCount uses the filtered feed slice within a ~week window of the
  // playlist — typically 0 since the feed only spans ~2 weeks.
  const orphanEntries: OrphanEntry[] = useMemo(() => {
    const WEEK_MS = 7 * 86400000;
    return orphanGroups.map(({ group }) => {
      const pl = playlistByTitle.get(group.playlistTitle);
      const plTracks = pl?.tracks ?? [];
      const existingCount = pl?.track_count ?? plTracks.length;

      let newCount = 0;
      if (pl) {
        const existingUrns = new Set<string>();
        for (const t of plTracks) {
          if (t.urn) existingUrns.add(t.urn);
        }
        const anchor = group.start.getTime();
        const start = anchor - WEEK_MS;
        const end = anchor + 86400000;
        for (const t of allFilteredTracks) {
          if (!t.urn || existingUrns.has(t.urn)) continue;
          const ts = parseSCTimestamp(t.addedAt ?? t.created_at) ?? 0;
          if (ts >= start && ts <= end) newCount++;
        }
      }

      return {
        key: group.key,
        title: group.label,
        trackCount: existingCount + newCount,
        newCount,
      };
    });
  }, [orphanGroups, playlistByTitle, allFilteredTracks]);

  const visibleWeekGroups = useMemo(
    () => visibleGroups.map(({ group }) => group),
    [visibleGroups],
  );

  // Default selection: first visible group (current week wins)
  useEffect(() => {
    if (selectedId) return;
    const current = visibleWeekGroups.find((g) => g.isCurrent);
    const first = current ?? visibleWeekGroups[0];
    if (first) setSelectedId(weekNodeId(first.key));
  }, [selectedId, visibleWeekGroups, setSelectedId]);

  // Resolve the selected entry (week or orphan)
  const selectedEntry = useMemo(() => {
    if (!selectedId) return null;
    if (selectedId.startsWith("week:")) {
      const key = selectedId.slice("week:".length);
      return visibleGroups.find(({ group }) => group.key === key) ?? null;
    }
    if (selectedId.startsWith("orphan:")) {
      const key = selectedId.slice("orphan:".length);
      return orphanGroups.find(({ group }) => group.key === key) ?? null;
    }
    return null;
  }, [selectedId, visibleGroups, orphanGroups]);

  // Universe of tracks the filters operate on: the selected week/playlist's
  // tracks (existing playlist + new feed candidates, or the raw feed slice if
  // no playlist exists yet). Filter options (genres, duration bounds, counts)
  // and the toolbar totals are derived from this set so they match what the
  // user sees in the card — not the 2-week feed across all weeks.
  const selectedUniverse = useMemo<SCTrack[]>(() => {
    if (!selectedEntry) return [];
    const { group } = selectedEntry;
    const pl = playlistByTitle.get(group.playlistTitle);
    if (!pl) return group.tracks;
    const existingTracks = pl.tracks ?? [];
    const existingUrns = new Set(
      existingTracks.map((t) => t.urn).filter((u): u is string => !!u),
    );
    const newCandidates = group.tracks.filter(
      (t) => t.urn && !existingUrns.has(t.urn),
    );
    return [...existingTracks, ...newCandidates];
  }, [selectedEntry, playlistByTitle]);

  const schema = useMemo(
    () =>
      buildWeeklySchema({
        tracks: selectedUniverse,
        hasCollection: collectionIds.size > 0,
      }),
    [selectedUniverse, collectionIds],
  );

  // Counts for the filter toolbar, derived from the same universe so the
  // numbers match what the card renders.
  const { visibleCount, visibleTotal } = useMemo(() => {
    const filtered = selectedUniverse.filter(inPlaylistPredicate).length;
    return { visibleCount: filtered, visibleTotal: selectedUniverse.length };
  }, [selectedUniverse, inPlaylistPredicate]);

  const selectedCount = selectedIds.size;

  useTopBar({
    title: "Weekly Favorites",
    actions: (
      <div className="flex items-center gap-2">
        <ToggleGroup
          type="single"
          value={groupingMode ?? "weekly"}
          onValueChange={(v) => v && setGroupingMode(v as GroupingMode)}
          className="h-7"
        >
          <ToggleGroupItem value="weekly" className="h-7 px-3 text-xs">
            Weekly
          </ToggleGroupItem>
          <ToggleGroupItem value="biweekly" className="h-7 px-3 text-xs">
            Twice a week
          </ToggleGroupItem>
        </ToggleGroup>
        <Button
          variant="ghost"
          size="sm"
          className="h-7 w-7 p-0"
          onClick={reload}
          title="Refresh tracks"
        >
          <RefreshCw className={`size-3.5 ${loading ? "animate-spin" : ""}`} />
        </Button>
      </div>
    ),
  });

  return (
    <div className="flex min-h-0 flex-1">
      <WeeklyTreePanel
        weeks={weekEntries}
        orphans={orphanEntries}
        selectedId={selectedId ?? ""}
        onSelect={setSelectedId}
      />

      <div className="flex min-w-0 flex-1 flex-col overflow-hidden">
        <FiltersToolbar
          schema={schema}
          state={filterState}
          onChange={setFilter}
          onClearAll={clearFilters}
          filtered={visibleCount}
          total={visibleTotal}
          defaultOpen
          trailing={
            <>
              {selectedCount > 0 && (
                <span>{selectedCount.toLocaleString()} selected</span>
              )}
              {loading && <span>(loading…)</span>}
            </>
          }
        />

        <div className="flex min-h-0 flex-1 flex-col">
          {error && (
            <div className="text-destructive px-1 text-sm">{error}</div>
          )}

          {loading && tracks.length === 0 && (
            <div className="text-muted-foreground flex h-48 flex-col items-center justify-center gap-3">
              <LogoSpinner />
              <span className="text-sm">
                Loading tracks from followed artists…
              </span>
            </div>
          )}

          {!loading && tracks.length === 0 && !error && (
            <div className="text-muted-foreground flex h-48 flex-col items-center justify-center gap-2">
              <CalendarDays className="size-8 opacity-30" />
              <span className="text-sm">
                No tracks found in the last 2 weeks.
              </span>
            </div>
          )}

          {!loading && tracks.length > 0 && !selectedEntry && (
            <div className="text-muted-foreground flex h-48 flex-col items-center justify-center gap-2">
              <CalendarDays className="size-8 opacity-30" />
              <span className="text-sm">Select a week from the sidebar.</span>
            </div>
          )}

          {selectedEntry && (
            <WeeklyGroupCard
              key={selectedEntry.group.key}
              group={selectedEntry.group}
              filteredTracks={selectedEntry.filteredTracks}
              selectedIds={selectedIds}
              onToggleSelect={toggleSelect}
              onRangeSelect={rangeSelect}
              onSelectAll={selectGroupAll}
              onDeselectAll={deselectGroup}
              collectionIds={collectionIds}
              existingPlaylist={playlistByTitle.get(
                selectedEntry.group.playlistTitle,
              )}
              playlistDescription={
                selectedEntry.group.start.getTime() > 0
                  ? buildPlaylistDescription(selectedEntry.group)
                  : ""
              }
              onPlaylistsReload={reloadPlaylists}
              filterTrack={inPlaylistPredicate}
            />
          )}

          {loading && tracks.length > 0 && (
            <div className="text-muted-foreground mt-3 flex items-center gap-2 px-1 py-2 text-xs">
              <LogoSpinner className="size-4" />
              Loading more… ({loaded.toLocaleString()} so far)
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
