'use client';

import { useState, useCallback, useEffect, useMemo } from 'react';
import { useQueryState } from 'nuqs';
import { RefreshCw, CalendarDays } from 'lucide-react';
import { useFollowingsTracks } from './use-followings-tracks';
import { useWeeklyPlaylists } from './use-weekly-playlists';
import { useWeeklyGroups, type GroupingMode } from './use-weekly-groups';
import { useWeeklyFilter, type WeeklyFilterOptions } from './use-weekly-filter';
import { WeeklyGroupCard } from '@/components/weekly-group-card';
import { LikesFilterBar } from '@/components/likes-filter-bar';
import { PageHeader } from '@/components/page-header';
import { LogoSpinner } from '@/components/logo-spinner';
import { Button } from '@/components/ui/button';
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group';
import { api } from '@/lib/api';
import { getMyLikedTracks, fetchLikesPage, type SCTrack, type SCPlaylist } from '@/lib/soundcloud';

function extractId(track: SCTrack): number | undefined {
  if (!track.urn) return undefined;
  const parts = track.urn.split(':');
  return parseInt(parts[parts.length - 1], 10) || undefined;
}

function buildPlaylistDescription(group: { start: Date; end: Date; playlistTitle: string }): string {
  const start = group.start.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric', timeZone: 'UTC' });
  const end = new Date(group.end.getTime() - 86400000).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric', timeZone: 'UTC' });

  // Calendar week
  const d = new Date(group.end.getTime() - 86400000);
  const dayNum = d.getUTCDay() || 7;
  const thu = new Date(d);
  thu.setUTCDate(d.getUTCDate() + 4 - dayNum);
  const yearStart = new Date(Date.UTC(thu.getUTCFullYear(), 0, 1));
  const cw = Math.ceil((((thu.getTime() - yearStart.getTime()) / 86400000) + 1) / 7);

  return `Autogenerated set of tracks from followed artists.\n${start} – ${end}, CW ${cw}`;
}

export default function WeeklyPage() {
  const [groupingMode, setGroupingMode] = useQueryState<GroupingMode>('mode', {
    defaultValue: 'weekly',
    parse: (v) => (v === 'biweekly' ? 'biweekly' : 'weekly'),
    serialize: (v) => v,
  });

  const { tracks, loading, loaded, error, reload } = useFollowingsTracks();
  const { playlists: weeklyPlaylists, seenTrackIds, reload: reloadPlaylists } = useWeeklyPlaylists();

  const groups = useWeeklyGroups(tracks, groupingMode);

  // Collection IDs
  const [collectionIds, setCollectionIds] = useState<Set<number>>(new Set());
  useEffect(() => {
    api.getCollectionSoundcloudIds()
      .then((ids) => setCollectionIds(new Set(ids)))
      .catch(() => {});
  }, []);

  // Global filter state
  const [search, setSearch] = useState('');
  const [genres, setGenres] = useState<string[]>([]);
  const [minDuration, setMinDuration] = useState<number | null>(null);
  const [maxDuration, setMaxDuration] = useState<number | null>(null);
  const [excludeSeen, setExcludeSeen] = useState(true);
  const [inCollection, setInCollection] = useState<boolean | null>(null);
  const [excludeOwnLikes, setExcludeOwnLikes] = useState(true);
  const [trackType, setTrackType] = useState<'track' | 'set' | null>('track');

  // Liked track IDs — fetched lazily when the filter is first enabled
  const [likedTrackIds, setLikedTrackIds] = useState<Set<number> | null>(null);
  useEffect(() => {
    if (!excludeOwnLikes || likedTrackIds !== null) return;
    let cancelled = false;
    async function fetchAllLikedIds() {
      const ids = new Set<number>();
      let page = await getMyLikedTracks(200);
      for (const t of page.collection ?? []) {
        const parts = (t.urn ?? '').split(':');
        const id = parseInt(parts[parts.length - 1], 10);
        if (!isNaN(id)) ids.add(id);
      }
      while (page.next_href && !cancelled) {
        page = await fetchLikesPage(page.next_href);
        for (const t of page.collection ?? []) {
          const parts = (t.urn ?? '').split(':');
          const id = parseInt(parts[parts.length - 1], 10);
          if (!isNaN(id)) ids.add(id);
        }
      }
      if (!cancelled) setLikedTrackIds(ids);
    }
    fetchAllLikedIds().catch(() => {});
    return () => { cancelled = true; };
  }, [excludeOwnLikes, likedTrackIds]);

  const filterOptions: WeeklyFilterOptions = {
    search,
    genres,
    minDuration,
    maxDuration,
    trackType,
    excludeSeen,
    inCollection,
    excludeOwnLikes,
  };

  // Apply filter to all tracks to get availableGenres and filtered counts
  const { filteredTracks: allFilteredTracks, availableGenres } = useWeeklyFilter(
    tracks,
    filterOptions,
    seenTrackIds,
    collectionIds,
    likedTrackIds ?? undefined,
  );

  // Per-group filtered tracks
  const groupsWithFilteredTracks = useMemo(() => {
    const filteredSet = new Set(allFilteredTracks);
    return groups.map((group) => ({
      group,
      filteredTracks: group.tracks.filter((t) => filteredSet.has(t)),
    }));
  }, [groups, allFilteredTracks]);

  // Global selection state (across all groups)
  const [selectedIds, setSelectedIds] = useState<Set<number>>(new Set());

  const toggleSelect = useCallback((id: number) => {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }, []);

  const rangeSelect = useCallback((ids: number[]) => {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      ids.forEach((id) => next.add(id));
      return next;
    });
  }, []);

  const selectGroupAll = useCallback((ids: number[]) => {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      ids.forEach((id) => next.add(id));
      return next;
    });
  }, []);

  const deselectGroup = useCallback((ids: number[]) => {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      ids.forEach((id) => next.delete(id));
      return next;
    });
  }, []);

  // Build playlist title map: playlistTitle -> SCPlaylist
  const playlistByTitle = useMemo(() => {
    const map = new Map<string, SCPlaylist>();
    for (const pl of weeklyPlaylists) {
      map.set((pl.title ?? '').trim(), pl);
    }
    return map;
  }, [weeklyPlaylists]);

  // Playlists that don't match any feed group (outside the 2-week feed window)
  const orphanGroups = useMemo(() => {
    const feedPlaylistTitles = new Set(groups.map((g) => g.playlistTitle));
    return weeklyPlaylists
      .filter((pl) => !feedPlaylistTitles.has((pl.title ?? '').trim()))
      .map((pl) => {
        const createdAt = (pl as Record<string, unknown>).created_at as string | undefined;
        const date = createdAt ? new Date(createdAt) : new Date(0);
        return {
          group: {
            key: `orphan-${(pl as Record<string, unknown>).urn ?? pl.title}`,
            label: (pl.title ?? '').trim(),
            playlistTitle: (pl.title ?? '').trim(),
            start: date,
            end: date,
            tracks: [],
            isCurrent: false,
          },
          filteredTracks: [] as SCTrack[],
        };
      })
      // Sort most-recent first by created_at
      .sort((a, b) => b.group.start.getTime() - a.group.start.getTime());
  }, [weeklyPlaylists, groups]);

  const totalFilteredCount = allFilteredTracks.length;
  const selectedCount = selectedIds.size;

  return (
    <div className="flex flex-col h-full min-h-0">
      <PageHeader
        title="Weekly Favorites"
        actions={
          <div className="flex items-center gap-2">
            <ToggleGroup
              type="single"
              value={groupingMode ?? 'weekly'}
              onValueChange={(v) => v && setGroupingMode(v as GroupingMode)}
              className="h-7"
            >
              <ToggleGroupItem value="weekly" className="h-7 text-xs px-3">Weekly</ToggleGroupItem>
              <ToggleGroupItem value="biweekly" className="h-7 text-xs px-3">Twice a week</ToggleGroupItem>
            </ToggleGroup>
            <Button
              variant="ghost"
              size="sm"
              className="h-7 w-7 p-0"
              onClick={reload}
              title="Refresh tracks"
            >
              <RefreshCw className={`size-3.5 ${loading ? 'animate-spin' : ''}`} />
            </Button>
          </div>
        }
      >
        <LikesFilterBar
          search={search}
          onSearchChange={setSearch}
          genres={genres}
          onGenresChange={setGenres}
          availableGenres={availableGenres}
          minDuration={minDuration}
          maxDuration={maxDuration}
          onMinDurationChange={setMinDuration}
          onMaxDurationChange={setMaxDuration}
          trackType={trackType}
          onTrackTypeChange={setTrackType}
          excludeMyLikes={excludeSeen}
          onExcludeMyLikesChange={setExcludeSeen}
          showExcludeMyLikes={true}
          excludeMyLikesLabel="Exclude previously added"
          excludeOwnLikes={excludeOwnLikes}
          onExcludeOwnLikesChange={setExcludeOwnLikes}
          showExcludeOwnLikes={true}
          inCollection={inCollection}
          onInCollectionChange={setInCollection}
          showInCollection={collectionIds.size > 0}
          filteredCount={totalFilteredCount}
          totalCount={tracks.length}
          loading={loading}
          selectedCount={selectedCount}
        />
      </PageHeader>

      <div className="flex-1 overflow-y-auto min-h-0 p-4 space-y-3">
        {error && (
          <div className="text-sm text-destructive px-1">{error}</div>
        )}

        {loading && tracks.length === 0 && (
          <div className="flex flex-col items-center justify-center h-48 gap-3 text-muted-foreground">
            <LogoSpinner />
            <span className="text-sm">Loading tracks from followed artists…</span>
          </div>
        )}

        {!loading && tracks.length === 0 && !error && (
          <div className="flex flex-col items-center justify-center h-48 gap-2 text-muted-foreground">
            <CalendarDays className="size-8 opacity-30" />
            <span className="text-sm">No tracks found in the last 2 weeks.</span>
          </div>
        )}

        {groupsWithFilteredTracks
          .filter(({ filteredTracks, group }) =>
            filteredTracks.length > 0 || playlistByTitle.has(group.playlistTitle),
          )
          .map(({ group, filteredTracks }, i) => (
            <WeeklyGroupCard
              key={group.key}
              group={group}
              filteredTracks={filteredTracks}
              selectedIds={selectedIds}
              onToggleSelect={toggleSelect}
              onRangeSelect={rangeSelect}
              onSelectAll={selectGroupAll}
              onDeselectAll={deselectGroup}
              collectionIds={collectionIds}
              existingPlaylist={playlistByTitle.get(group.playlistTitle)}
              defaultExpanded={i === 0}
              playlistDescription={buildPlaylistDescription(group)}
              onPlaylistsReload={reloadPlaylists}
              trackType={trackType}
            />
          ))}

        {orphanGroups.map(({ group, filteredTracks }) => (
          <WeeklyGroupCard
            key={group.key}
            group={group}
            filteredTracks={filteredTracks}
            selectedIds={selectedIds}
            onToggleSelect={toggleSelect}
            onRangeSelect={rangeSelect}
            onSelectAll={selectGroupAll}
            onDeselectAll={deselectGroup}
            collectionIds={collectionIds}
            existingPlaylist={playlistByTitle.get(group.playlistTitle)}
            defaultExpanded={false}
            playlistDescription=""
            onPlaylistsReload={reloadPlaylists}
          />
        ))}

        {loading && tracks.length > 0 && (
          <div className="flex items-center gap-2 text-xs text-muted-foreground px-1 py-2">
            <LogoSpinner className="size-4" />
            Loading more… ({loaded.toLocaleString()} so far)
          </div>
        )}
      </div>
    </div>
  );
}
